In [37]:
import pandas as pd
import numpy as np

# import matplotlib
import matplotlib.pyplot as plt
# import seaborn
import seaborn as sns
%matplotlib inline

In [42]:
df = pd.read_csv("iowa-sample.csv")
print(df.loc[1])

Invoice/Item Number                          S23102300041
Date                                           12/20/2014
Store Number                                         4346
Store Name                                 Roy's Foodland
Address                                      105 PEARL ST
City                                           SHELLSBURG
Zip Code                                            52332
Store Location               POINT (-91.869285 42.094155)
County Number                                           6
County                                             Benton
Category                                          1012100
Category Name                           CANADIAN WHISKIES
Vendor Number                                         115
Vendor Name              Constellation Wine Company, Inc.
Item Number                                         11774
Item Description                             Black Velvet
Pack                                                   24
Bottle Volume 

In [45]:
print(len(df["Store Number"].unique()))
print(len(df["Store Name"].unique()))
print(len(df["Address"].unique()))
print(len(df["City"].unique()))
print(len(df["Zip Code"].unique()))
print(len(df["County Number"].unique()))
print(len(df["County"].unique()))
print(len(df["Category"].unique()))
print(len(df["Category Name"].unique()))
print(len(df["Vendor Number"].unique()))
print(len(df["Vendor Name"].unique()))
print(len(df["Item Number"].unique()))
print(len(df["Item Description"].unique()))

# df.drop(["Store Nunber", "Address", "County Number", 
#             "Category", "Vendor Number"], axis=1, inplace=True)


531
528
530
198
229
92
92
57
57
39
39
587
430


In [25]:
df_small = df.head()
df_small = df_small.convert_dtypes()

df_small["Date"] = pd.to_datetime(df_small["Date"], format="%m/%d/%Y")

df_small["Store Name"] = df_small["Store Name"].astype('category')
df_small["City"] = df_small["City"].astype('category')
df_small["Zip Code"] = df_small["Zip Code"].astype('category')

df_small.dtypes

Invoice/Item Number              string
Date                     datetime64[ns]
Store Number                      Int64
Store Name                     category
City                           category
Zip Code                       category
Store Location                   string
County Number                     Int64
County                           string
Category                          Int64
Category Name                    string
Vendor Number                     Int64
Vendor Name                      string
Item Number                       Int64
Item Description                 string
Pack                              Int64
Bottle Volume (ml)                Int64
State Bottle Cost               float64
State Bottle Retail             float64
Bottles Sold                      Int64
Sale (Dollars)                  float64
Volume Sold (Liters)            float64
Volume Sold (Gallons)           float64
dtype: object

In [7]:
pd.get_dummies(df_small["City"])

CEDAR RAPIDS  DES MOINES  GLENWOOD  SHELLSBURG  SIOUX CITY
0             0           1         0           0           0
1             0           0         0           1           0
2             1           0         0           0           0
3             0           0         1           0           0
4             0           0         0           0           1

In [183]:
class LR:
    
    def fit(self, X_train, y_train):
        # create vector of ones...
        ones = np.ones(shape=len(X_train))[..., None]
        #...and add to feature matrix
        X = np.concatenate((ones, X_train), 1)
        #calculate coefficients using closed-form solution
        self.coeffs = inv(X.transpose().dot(X)).dot(X.transpose()).dot(y_train)
        
    def predict(self, X_test):
        ones = np.ones(shape=len(X_test))[..., None]
        X_test = np.concatenate((ones, X_test), 1)
        y_hat = X_test.dot(self.coeffs)
        return y_hat

# # extract the feature names of the boston data set and prepend the intercept
# feature_names = np.insert(boston.feature_names, 0, 'INT')

# # collect results into a DataFrame for pretty printing
# results = pd.DataFrame({'coeffs':coeffs}, index=feature_names)


array([13.5724999 , 12.41648163, 11.26046336, 10.1044451 ,  8.94842683,
        7.79240856,  6.6363903 ,  5.48037203,  4.32435376,  3.1683355 ,
        2.01231723,  0.85629897])

In [184]:
from sklearn.linear_model import LinearRegression

data_dir = "https://dlsun.github.io/pods/data/"
bordeaux_df = pd.read_csv(data_dir + "bordeaux.csv",
                          index_col="year")
bordeaux_train = bordeaux_df.loc[:1980].copy()
bordeaux_test = bordeaux_df.loc[1980:].copy()

X_train = bordeaux_train[["age"]]
X_test = bordeaux_test[["age"]]
y_train = bordeaux_train["price"]


In [185]:
model = LinearRegression()
model.fit(X=X_train, y=y_train)
model.predict(X=X_test)

array([13.5724999 , 12.41648163, 11.26046336, 10.1044451 ,  8.94842683,
        7.79240856,  6.6363903 ,  5.48037203,  4.32435376,  3.1683355 ,
        2.01231723,  0.85629897])

In [186]:
model = LR()
model.fit(X_train, y_train)
model.predict(X_test)

array([13.5724999 , 12.41648163, 11.26046336, 10.1044451 ,  8.94842683,
        7.79240856,  6.6363903 ,  5.48037203,  4.32435376,  3.1683355 ,
        2.01231723,  0.85629897])

In [188]:
bordeaux_train["log(price)"] = np.log(bordeaux_train["price"])
X=bordeaux_train[["summer", "win", "har", "age"]]
y=bordeaux_train["log(price)"]

ashen_model = LinearRegression()
ashen_model.fit(
    X=bordeaux_train[["summer", "win", "har", "age"]],
    y=bordeaux_train["log(price)"]
)
ashen_model.predict(
    X=bordeaux_test[["summer", "win", "har", "age"]]
)

array([2.77507496, 3.17926885, 3.4231464 , 3.71919787, 2.83391541,
       3.48195778, 2.4330387 , 2.91879638, 3.5924235 , 3.97294747,
       4.04789338, 3.14087609])

In [190]:
model = LR()
model.fit(X, y)
X_test = bordeaux_test[["summer", "win", "har", "age"]]
model.predict(X_test)

array([2.77507496, 3.17926885, 3.4231464 , 3.71919787, 2.83391541,
       3.48195778, 2.4330387 , 2.91879638, 3.5924235 , 3.97294747,
       4.04789338, 3.14087609])